apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-green
  labels:
    app: aceest-fitness
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest-fitness
      version: green
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: green
    spec:
      containers:
      - name: aceest-fitness-container
        image: aniruddha404/aceest_fitness_app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-service
spec:
  selector:
    app: aceest-fitness
    version: green
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort
