apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest-fitness
      release: canary
  template:
    metadata:
      labels:
        app: aceest-fitness
        release: canary
    spec:
      containers:
      - name: aceest-fitness-container
        image: aniruddha404/aceest_fitness_app:v1.42
        ports:
        - containerPort: 5000
